[package]
name = "docxtools"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9"
zip = "0.6"
walkdir = "2.3"
xml_dom = "0.2"
clap = { version = "4.3.19", features = ["derive"] }

[[bin]]
name = "docxtools"
path = "src/bin/main.rs"
