version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.72
    steps:
      - checkout
      - run: cargo build --release
  test:
    docker:
      - image: cimg/rust:1.72
    steps:
      - checkout
      - run: cargo test

workflows:
  build_and_test:
    jobs:
      - build
      - test
